### ISSUE TITLE
What happened if the future dies before the promise sets the result?

### ISSUE THREAD

**Issue by jamboree** [ned14/boost.outcome#4] opened 2015-09-10 13:17 UTC
Here's an inconsistency between the `std` and your version.

```c++
#include <cstdlib>
#include <iostream>
#include <future>
#include <boost/outcome/future.hpp>

namespace lw = boost::outcome::lightweight_futures;

int main(int argc, char *argv[])
{
    try
    {
        lw::promise<int> p;
        //std::promise<int> p;
        p.get_future();
        p.set_value(1);
        std::cout << "done\n";
    }
    catch (std::exception& e)
    {
        std::cout << e.what() << "\n";
    }

    return EXIT_SUCCESS;
}
```

The `std` version prints `done`, but the `lw` version throws an exception `no state`.

Is the inconsistency by design or is it a bug?

**Comment by ned14** [comment] 2015-09-10 13:46
> Is the inconsistency by design or is it a bug?

This behaviour is by design :) STL implementations have surprising variations in their interpretations of the standard. Mine is no different.

I agree it's a particularly aggressive interpretation of the standard. I decided that shared state only exists if some state is shared - the standard allows "hanging" shared state using the sequence your code describes, but I would suggest that is a bug not a feature because code which silently sinks setting state into orphaned promises is just as buggy as code trying to get from an orphaned future. This may potentially be a candidate for a LEWG defect, if it isn't already in there.

What should be the case (I need to add a test for this, hence leaving this issue open until I add such a test) is that if you use the future to schedule a continuation and then destroy the future, setting the promise should no longer throw because now there is a destination for the state set. If it does throw, that's a bug and isn't intended.

I also don't see any reason a config macro can't have LW futures behave "normally" here.

BTW thanks for all these issues. They are proving very valuable to me.

**Comment by jamboree** [comment] 2015-09-10 14:11
>This behaviour is by design :) STL implementations have surprising variations in their interpretations of the standard. Mine is no different.

At least g++, clang and MSVC give me the same result with their `std` implementation.

>if you use the future to schedule a continuation and then destroy the future, setting the promise should no longer throw because now there is a destination for the state set. If it does throw, that's a bug and isn't intended

A quick experiment:
```c++
p.get_future().then([](auto&&) {});
````
Still, it's `no state`, bug now?

>BTW thanks for all these issues. They are proving very valuable to me.

FWIW, I'm playing your LW future with my [CO2](https://github.com/jamboree/co2) library + ASIO, here's the code that adapts it for stackless coroutine and `asio::async_result`, if you're interested:

https://gist.github.com/jamboree/d769ec6a3933117d47c5

**Comment by ned14** [comment] 2015-09-10 15:11
> A quick experiment:
>
> > p.get_future().then([](auto&&) {});
>
> Still, it's no state, bug now?

Definitely yes. When I wrote my earlier reply I had a feeling that if I wasn't testing for the behaviour I intended which I wasn't, I probably foobared it as I usually do.

> https://gist.github.com/jamboree/d769ec6a3933117d47c5

Very nice, thank you. I've linked that into the docs actually.

Out of interest, how are your experiments going? Have you seen any benefits or penalties? Or are they just too buggy and non-conforming to be useful yet?

**Comment by jamboree** [comment] 2015-09-10 15:43
>Out of interest, how are your experiments going? Have you seen any benefits or penalties? Or are they just too buggy and non-conforming to be useful yet?

FYI, here's the timing that shows the latency introduced by different ways using ASIO: [code](https://gist.github.com/jamboree/5bf7705aa8d1be06bac1)

```
[callback]
 0.008950s wall, 0.000000s user + 0.000000s system = 0.000000s CPU (n/a%)
[co2+awaitable]
 0.008499s wall, 0.015600s user + 0.000000s system = 0.015600s CPU (183.5%)
[co2+LW] <- YOURS
 0.017083s wall, 0.015600s user + 0.000000s system = 0.015600s CPU (91.3%)
[Boost.Coroutine]
 0.012686s wall, 0.000000s user + 0.015600s system = 0.015600s CPU (123.0%)
```

As you can see, [co2+awaitable] is close to metal, while [co2+LW] is most expensive, which is a bit unexpected, I thought it should at least outperform [Boost.Coroutine]...

**Comment by ned14** [comment] 2015-09-10 19:04
It turns out I was missing a return statement. Fixed now, thanks for the report.

> As you can see, [co2+awaitable] is close to metal, while [co2+LW] is most expensive, which is a bit unexpected, I thought it should at least outperform [Boost.Coroutine]...

Me personally I found your results better than I was expecting by a fair margin :)

LW futures aren't supposed to be faster than anything but std::future, where I reckon they should be around 2x-4x faster depending. In the end, in your gist I can see at least four potential XCHG instructions each of which will cost 25-50 cycles plus at least one malloc + free for the continuation, so that's automatically going to be a lot slower than a Coroutine context switch.

Your results above are therefore surprisingly good :)

**Closed by ned14** 2015-09-10 19:04 UTC

**Comment by jamboree** [comment] 2015-09-11 01:59
For the sake of consistency, I think the case for `p.get_future()` and `p.get_future().then([](auto&&) {})` should give the same result.

This is how I think it: `return` in the continuation is conceptually the same as setting the result from the promise, and the future returned from `then` in this case also dies before there's a chance to set the result from the continuation, thus it should be either both throws or both not throws, the current design is inconsistent IMO.

**Comment by ned14** [comment] 2015-09-11 09:57
It's a fair point, and you can get that behaviour by defining BOOST_OUTCOME_SET_PROMISE_AFTER_FUTURE_IS_NOTHROW.

I'm going to see how during real world use the current behaviour falls out, and if it's a problem it's a very easy resolution.

**Comment by jamboree** [comment] 2015-09-11 13:06
The nothrow behavior is crucial to async/await style coroutine, otherwise your LW future cannot be used as the `Result` of the coroutine. The early examples I gave you only shows its usage as `Awaitable`, this time, I'll illustrate its usage as `Result`:

Typically you'll define some async tasks like below
```c++
future<void> task(Dispatcher& disp, ...)
{
    await disp.async_xxx(...);
    await disp.async_xxx(...);
}
```

and use them as
```c++
Dispatcher disp;
// launch some tasks
for (...)
    task(disp, ...); // we don't care about the result of individual task
// then run
disp.run();
```

Given your current semantic (i.e. throw if no receiving future), the program will crash, because we don't store the result of `task(disp, ...)` anywhere, after the `task` completes, it calls `promise.set_value` which throws `no state` error and that exception is again catch by `promise.set_exception` which will again throw `no state` error and eventually it will cause the program to terminate because the coroutine call is declared as `noexcept`.

Of course, in the example above if we store the results for each `task` and keep them alive after `disp.run()`, the program won't crash, but it's quite inefficient and not always possible, consider the [server example](https://github.com/jamboree/act#example), it's impossible to store the results for each session because they're conceptually infinite.

**Comment by ned14** [comment] 2015-09-12 12:37
Ok, if it's an issue for you in practice, I can default to STL behaviour instead. I'll push that update shortly.

**Comment by ned14** [comment] 2015-09-23 16:30
Tongari I have been thinking about the performance thing. Would it be useful to you if these futures did no locking? They would be unsafe for concurrent use, but would perform several times faster. Like seastar futures.

**Comment by jamboree** [comment] 2015-09-23 16:54
I think in most case we'll need concurrent use (e.g. in ASIO one can run the same io_service in different threads), but in the benchmark above that's not needed. At least, it'd be interesting to compare the results.

**Comment by ned14** [comment] 2015-09-23 17:57
It should roughly double the single threaded performance, so that should eliminate the performance differential you observed.

By "unsafe for concurrent use", I mean:

1. You cannot move neither future nor promise concurrently. In other words, never move them after construction and you'll be fine.

2. This pattern becomes unsafe:

     std::promise<int> p;
     std::thread t([&] { p.set_value(42); });
     std::future<int> f = p.get_future();

This however would be fine:

     std::promise<int> p;
     std::future<int> f = p.get_future();
     std::thread t([&] { p.set_value(42); });
     f.get();

I can do lock free semantics in the latter case, but not elsewhere.

**Comment by jamboree** [comment] 2015-09-24 01:14
For await-style coroutine, the promise will never be moved, but the future will probably be moved.
In my CO2 emulation, at least one move is required on future, but with compiler support, I guess RVO and copy elision might help.

**Comment by ned14** [comment] 2015-09-24 04:38
Is the move ever able to occur concurrently to any other operation?

**Comment by jamboree** [comment] 2015-09-24 07:39
Depends on what it awaits on

```c++
lw::future<int> foo(...)
{
    return await std::async(...);
}

lw::future<void> bar(...)
{
    auto a(foo(...));
    await a;
}
```

Suppose `std::async` runs concurrently, then the `lw::future<int>` returns from `foo` may be moved concurrently when `foo` is still running. If the compiler is smart enough to apply RVO and copy elision, the move is not needed, but there's no such guarantee.

In the case of ASIO, e.g. `sock.async_read_some(..., use_lw_future)`, however, both the promise & future will be moved.
